name: Mentee application
description: Apply to take part in the astropy mentoring scheme as a mentee
title: "Mentee application - <your name>"
labels: ["application"]
assignees:
  - ''
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Please give your name
    validations:
      required: true
  - type: input
    id: slack
    attributes:
      label: Slack username
      description: Please give the username you use on Slack/matrix (if it's different to your GitHub username) so that we know who to associate the application with.
    validations:
      required: false
  - type: textarea
    id: role
    attributes:
      label: Which role would you like to apply for and why
      description: The aim of the mentoring program is to eventually enable you to join the astropy team. Let us know which role you are interested in and what interests you about it. This will help us find you a suitable mentor.
    validations:
      required: true
  - type: textarea
    id: contributions
    attributes:
      label: Astropy contributions
      description: Tell us what contributions you have made to astropy, either to the code base or to the community more generally if appropriate. Please provide links to relevant PRs to support your application.
  - type: textarea
    id: other
    attributes:
      label: Other info
      description: Use this section to provide any other information you think we should know about you or your application.
  - type: markdown
    attributes:
      value: |
        Thank you for applying to the astropy mentoring program. We will contact you as soon as we find a mentor for you.
